name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

isar_version: &isar_version 3.1.0 # define the version to be used


dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  intl: ^0.20.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - .env
