name: push_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  go_router: ^14.6.3
  google_sign_in: ^6.2.2
  google_sign_in_ios: ^5.7.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
